title: Leathanaigh de naoigcat
url: https://naoigcat.github.io/
author: naoigcat
github_username: naoigcat
description: >-
  It takes all the running you can do, to keep in the same place.
theme: minima
plugins:
  - jekyll-feed
google_analytics: UA-158986608-1
